# Generated by Django 3.1.3 on 2022-01-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_header', models.CharField(max_length=200, null=True)),
                ('date_posted', models.DateField()),
                ('blog_content', models.CharField(max_length=1000, null=True)),
                ('blog_image', models.FileField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('portfolio_image', models.FileField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=200, null=True)),
                ('prod_category', models.CharField(max_length=200, null=True)),
                ('prod_img', models.FileField(upload_to='img')),
                ('prod_price', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, null=True)),
                ('customer_testimony', models.CharField(max_length=200, null=True)),
                ('customer_image', models.FileField(upload_to='img')),
            ],
        ),
    ]
