# Generated by Django 3.1.3 on 2022-01-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ness_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationCake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gc_name', models.CharField(max_length=200, null=True)),
                ('gc_img', models.FileField(upload_to='img')),
                ('gc_price', models.IntegerField(null=True)),
            ],
        ),
    ]
